### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by marzn** [PatternAtlas/pattern-atlas-api#22]
This is a mix between a question, a suggestion and a bug report ;)

*The finding*
With commit https://github.com/PatternAtlas/pattern-atlas-api/commit/0604e52775a13edb6e1ded27edb6d170e14f5d6d the CORS policy is changed. Due to the new origin the PatternAtlas UI has to listen on port 80, which is the default for HTTP.

*The bug*
This breaks - at least for me - the development environment, where port 4200 is used for the Angular development server. This results in XHR beeing blocked by the browser.

*The question*
Is this intented? May the UI development port can be changed to port 80.

*Three suggestions*
 - Add port 4200 on localhost to the allowed origin
 - Or define spring profiles for different environments and easy switching, if that was the reason for the change
 - Or use the backend proxy in PatternAtlas UI develoment, like documented here: https://angular.io/guide/build#proxying-to-a-backend-server

**Comment by manuwei** [comment]
Ports were changed in the [last commit](https://github.com/PatternAtlas/pattern-atlas-api/commit/f735e4d2a0a8b9b1aea6650290638d42524dff46) so this issue can be closed
