### ISSUE TITLE
Read-Only Mode

### ISSUE THREAD

**Issue by mar-be** [PatternAtlas/pattern-atlas-api#37]
It should be possible to run the Pattern-Atlas in a read-only mode which just displays the patterns and does not allow any changes to them.

A possible solution is to allow only read access to the database.

**Comment by mar-be** [comment]
Coresponding issue: https://github.com/PatternAtlas/pattern-atlas-ui/issues/96

**Comment by mhinkie** [comment]
closing since read-only mode will be obsolete with API authentication
