### ISSUE TITLE
Verify and update privilege management

### ISSUE THREAD

**Issue by mhinkie** [PatternAtlas/pattern-atlas-api#42]
**Is your feature request related to a problem? Please describe.**
It is possible to change resources in Patternatlas in some cases because the privilege management is not complete in the API. See for example https://github.com/PatternAtlas/pattern-atlas-ui/issues/144
The API should check for the correct roles and privileges if data should be changed. 

**Describe the solution you'd like**
In this feature request, alls calls to the API should be examined if this is the case and if authentication works properly.

Before this issue can be adressed, Issue #43 has to be adressed.

**Comment by mhinkie** [comment]
Checks added for Issue and Candidate. 
TODO:
- Patterns and Pattern-Languages (will be done when promoting candidates to patterns is done)
- Create Guest user and Role, the API will implicitly select this user when no user is supplied (can be done by extending `ResourceSecurityExpressionRoot`)

**Comment by PhilWun** [comment]
Missing permission checks for Pattern Views and Pattern Languages were added in https://github.com/PatternAtlas/pattern-atlas-api/commit/829182b31819bb0fc4cc209da2ceed4e2292a40f.

**Comment by PhilWun** [comment]
Guest role added that is used for users who are not logged in https://github.com/PatternAtlas/pattern-atlas-api/commit/9b01014df14bd31cff045fb3f5c87de02f3db955

**Comment by mhinkie** [comment]
looks good to me, thank you!
